from enum import StrEnum

class IncidentStatus(StrEnum):
    DETECTED="DETECTED"; TRIAGED="TRIAGED"; INVESTIGATING="INVESTIGATING"; RCA_READY="RCA_READY"; ACTION_PROPOSED="ACTION_PROPOSED"; PENDING_APPROVAL="PENDING_APPROVAL"; EXECUTING="EXECUTING"; VERIFYING="VERIFYING"; RESOLVED="RESOLVED"; CLOSED="CLOSED"; ESCALATED="ESCALATED"; BLOCKED="BLOCKED"; FAILED="FAILED"; REOPENED="REOPENED"
class Severity(StrEnum):
    LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"; CRITICAL="CRITICAL"
