import type { AgentRun, Approval, ConfigWorkspace, DashboardSnapshot, Incident, IncidentWorkspace, Integration, QueueJob, ReviewDetail } from "../contracts/types";

export const previewTime = "2026-10-02T10:00:00Z";
const permission = (allowed: boolean, reason: string) => ({ allowed, reason });
export const incidentFixtures: Incident[] = [
  {
    id: "inc-1", display_id: "INC-2026-001", title: "강남점 냉장 보관 온도 이탈", severity: "CRITICAL", status: "PENDING_APPROVAL", store: "강남점", owner: "김민지", created_at: "2026-10-02T08:20:00Z", sla_due_at: "2026-10-02T12:20:00Z",
    timeline: ["DETECTED", "TRIAGED", "INVESTIGATING", "RCA_READY", "ACTION_PROPOSED", "PENDING_APPROVAL"].map((status, index) => ({ status: status as Incident["status"], occurred_at: `2026-10-02T0${8 + Math.floor(index / 4)}:${20 + (index % 4) * 10}:00Z` })),
    evidence: [
      { id: "ev-1", source: "냉장고 A 온도 센서", type: "센서 기록", summary: "상한 4°C를 34분 초과했습니다. 최고 온도는 8.1°C입니다.", confidence: 0.98, status: "AVAILABLE" },
      { id: "ev-2", source: "설비 점검 이력", type: "유지보수 기록", summary: "압축기 점검 주기가 14일 경과했고 냉각 효율 저하가 기록되었습니다.", confidence: 0.9, status: "AVAILABLE" },
      { id: "ev-3", source: "매장 관리자", type: "현장 확인", summary: "문 개방 이벤트는 정상 범위였고 식자재 입고 시각과 일치하지 않았습니다.", confidence: 0.8, status: "AVAILABLE" },
      { id: "ev-4", source: "입고 로트 정보", type: "재고 기록", summary: "영향 로트의 입고 온도 증빙을 추가 요청했습니다.", confidence: 0, status: "PENDING" },
    ],
    root_cause_candidates: [
      { id: "rca-1", summary: "냉각기 압축기 성능 저하", confidence: 0.82, supporting_evidence_ids: ["ev-1", "ev-2"], counter_evidence_ids: [] },
      { id: "rca-2", summary: "입고 작업 중 냉장고 문 장시간 개방", confidence: 0.21, supporting_evidence_ids: ["ev-1"], counter_evidence_ids: ["ev-3"] },
    ],
    corrective_actions: [{ id: "ca-1", summary: "영향 재고 격리 및 냉각기 점검", risk_level: "HIGH", expected_effect: "식품 안전 위험을 차단하고 냉장 성능을 복구합니다.", verification_criteria: "온도 2~4°C를 2시간 유지하고 격리 재고의 처리 기록을 확인합니다.", status: "PROPOSED" }],
    verification: { id: "ver-1", result: "INCONCLUSIVE", summary: "승인 및 조치 완료 후 연속 온도 기록을 확인합니다." },
  },
  { id: "inc-2", display_id: "INC-2026-002", title: "홍대점 배달 지연 VOC 급증", severity: "HIGH", status: "INVESTIGATING", store: "홍대점", owner: "박준호", created_at: "2026-10-02T07:10:00Z", sla_due_at: "2026-10-02T15:10:00Z", timeline: [{ status: "DETECTED", occurred_at: "2026-10-02T07:10:00Z" }, { status: "TRIAGED", occurred_at: "2026-10-02T07:15:00Z" }, { status: "INVESTIGATING", occurred_at: "2026-10-02T07:20:00Z" }], evidence: [{ id: "ev-5", source: "고객 리뷰 집계", type: "VOC", summary: "최근 2시간 배달 지연 언급이 기준 대비 3배 증가했습니다.", confidence: 0.92, status: "AVAILABLE" }], root_cause_candidates: [], corrective_actions: [] },
  { id: "inc-3", display_id: "INC-2026-003", title: "성수점 알레르기 표시 누락 확인", severity: "HIGH", status: "DETECTED", store: "성수점", owner: "이수현", created_at: "2026-10-02T09:30:00Z", sla_due_at: "2026-10-02T13:30:00Z", timeline: [{ status: "DETECTED", occurred_at: "2026-10-02T09:30:00Z" }], evidence: [], root_cause_candidates: [], corrective_actions: [] },
  { id: "inc-4", display_id: "INC-2026-004", title: "판교점 입고 로트 정보 불일치", severity: "MEDIUM", status: "BLOCKED", store: "판교점", owner: "최유진", created_at: "2026-10-02T04:00:00Z", sla_due_at: "2026-10-02T08:00:00Z", timeline: [{ status: "DETECTED", occurred_at: "2026-10-02T04:00:00Z" }, { status: "BLOCKED", occurred_at: "2026-10-02T06:00:00Z" }], evidence: [], root_cause_candidates: [], corrective_actions: [] },
  { id: "inc-5", display_id: "INC-2026-005", title: "잠실점 포장 누락 개선 효과 확인", severity: "LOW", status: "RESOLVED", store: "잠실점", owner: "정지우", created_at: "2026-10-01T01:00:00Z", sla_due_at: "2026-10-02T09:00:00Z", timeline: [{ status: "VERIFYING", occurred_at: "2026-10-02T05:00:00Z" }, { status: "RESOLVED", occurred_at: "2026-10-02T09:00:00Z" }], evidence: [], root_cause_candidates: [], corrective_actions: [{ id: "ca-5", summary: "포장 체크리스트 적용", risk_level: "LOW", expected_effect: "구성품 누락 감소", verification_criteria: "30건 연속 누락 없음", status: "EXECUTED" }], verification: { id: "ver-5", result: "PASS", summary: "30건 연속 확인 결과 누락이 없었습니다.", verified_at: "2026-10-02T09:00:00Z" } },
  { id: "inc-6", display_id: "INC-2026-006", title: "강남점 음료 누수 재발", severity: "MEDIUM", status: "REOPENED", store: "강남점", owner: "김민지", created_at: "2026-10-01T02:00:00Z", sla_due_at: "2026-10-02T11:00:00Z", timeline: [{ status: "VERIFYING", occurred_at: "2026-10-02T06:00:00Z" }, { status: "REOPENED", occurred_at: "2026-10-02T09:00:00Z" }], evidence: [], root_cause_candidates: [], corrective_actions: [], verification: { id: "ver-6", result: "FAIL", summary: "샘플 20건 중 2건에서 누수가 재발했습니다.", verified_at: "2026-10-02T09:00:00Z" } },
];
export const workspaceFixtures: Record<string, IncidentWorkspace> = Object.fromEntries(incidentFixtures.map((item, index) => [item.id, {
  priority: index === 0 ? "P1" : index < 3 ? "P2" : "P3",
  tasks: index === 0 ? [{ id: "task-1", title: "영향 재고 격리 준비", owner: "강남점 관리자", due_at: "2026-10-02T11:00:00Z", status: "PENDING" }, { id: "task-2", title: "설비 점검 일정 확인", owner: "설비 담당자", due_at: "2026-10-02T12:00:00Z", status: "RUNNING" }] : [],
  actions: { investigate: permission(false, "조사 실행은 향후 작업 API 연결 후 제공됩니다."), propose_action: permission(false, "조치 제안은 원인 분석 API 연결 후 제공됩니다."), execute: permission(false, "실행 API와 승인 확인이 연결되기 전에는 조치를 실행할 수 없습니다.") },
}]));
export const approvalFixtures: Approval[] = [{ id: "apr-1", incident_id: "inc-1", type: "시정·예방 조치 검토", risk_level: "HIGH", requester: "조치 제안 담당", requested_at: "2026-10-02T09:15:00Z", evidence_completeness: 92, status: "PENDING", actions: { approve: permission(true, "필수 증거가 충족되어 검토자가 승인할 수 있습니다."), edit: permission(true, "조치안 수정 내용을 남길 수 있습니다."), reject: permission(true, "반려 사유와 함께 재검토를 요청할 수 있습니다."), request_more_evidence: permission(true, "부족한 근거를 지정해 추가 수집을 요청할 수 있습니다.") } }, { id: "apr-2", incident_id: "inc-4", type: "입고 정보 정합성 검토", risk_level: "MEDIUM", requester: "품질 운영 담당", requested_at: "2026-10-02T07:00:00Z", evidence_completeness: 45, status: "PENDING", actions: { approve: permission(false, "공급사 로트 증빙이 없어 현재는 승인할 수 없습니다."), edit: permission(true, "보완할 조치 내용을 작성할 수 있습니다."), reject: permission(true, "검토 요청을 반려할 수 있습니다."), request_more_evidence: permission(true, "공급사 로트 증빙을 요청해 주세요.") } }];
export const reviewFixtures: Record<string, ReviewDetail> = Object.fromEntries(approvalFixtures.map((approval) => {
  const incident = incidentFixtures.find((item) => item.id === approval.incident_id)!;
  return [approval.id, { approval_id: approval.id, incident_display_id: incident.display_id, incident_title: incident.title, proposed_action: incident.corrective_actions[0]?.summary ?? "공급사 원본 증빙 확보 후 로트 매핑을 수정합니다.", expected_effect: incident.corrective_actions[0]?.expected_effect ?? "입고 이력 추적성을 복구합니다.", verification_criteria: incident.corrective_actions[0]?.verification_criteria ?? "입고 항목과 공급사 증빙 일치 여부 확인", due_at: incident.sla_due_at, evidence: incident.evidence, history: [{ occurred_at: approval.requested_at, actor: approval.requester, summary: "검토 요청을 등록했습니다." }] }];
}));
export const integrationFixtures: Integration[] = [{ id: "pos", name: "POS 판매 데이터", category: "거래", description: "주문·매출·취소 데이터를 표준 거래 모델로 연결합니다.", status: "HEALTHY", last_success_at: "2026-10-02T09:58:00Z", canonical_model: "Transaction", mappings: [{ source: "saleAmount", target: "total_amount" }, { source: "shop_code", target: "store_id" }], sync: { started_at: "2026-10-02T09:57:00Z", ended_at: "2026-10-02T09:58:00Z", read_count: 1240, written_count: 1232, skipped_count: 8, error_count: 0, cursor_before: "tx-9800", cursor_after: "tx-11040" }, actions: { sync: permission(true, "미리보기 동기화 결과를 갱신할 수 있습니다.") } }, { id: "sensor", name: "온도 센서", category: "식품 안전", description: "냉장·냉동 설비의 온도 기록과 운영 예외를 연결합니다.", status: "HEALTHY", last_success_at: "2026-10-02T09:59:00Z", canonical_model: "TemperatureReading", mappings: [{ source: "temp_c", target: "temperature_celsius" }], sync: { started_at: "2026-10-02T09:58:00Z", ended_at: "2026-10-02T09:59:00Z", read_count: 360, written_count: 360, skipped_count: 0, error_count: 0, cursor_before: "sensor-740", cursor_after: "sensor-1100" }, actions: { sync: permission(true, "미리보기 동기화 결과를 갱신할 수 있습니다.") } }, { id: "supplier", name: "공급사 포털", category: "입고·재고", description: "입고 기록과 로트 증빙을 연결합니다.", status: "DEGRADED", last_success_at: "2026-10-02T09:42:00Z", error_summary: "lot_code 필드 형식이 변경되어 6건의 매핑을 보류했습니다.", canonical_model: "InventoryLot", mappings: [{ source: "lot_code", target: "lot_id" }], sync: { started_at: "2026-10-02T09:42:00Z", ended_at: "2026-10-02T09:43:00Z", read_count: 80, written_count: 74, skipped_count: 0, error_count: 6, cursor_before: "lot-120", cursor_after: "lot-200" }, actions: { sync: permission(false, "필드 매핑을 확인한 뒤 재동기화할 수 있습니다.") } }];
export const jobFixtures: QueueJob[] = [
  { id: "job-2204", type: "인시던트 증거 수집", tenant_id: "강남점", incident_id: "inc-1", status: "RUNNING", queued_at: "2026-10-02T09:57:00Z", attempts: 1, max_attempts: 3, priority: "P1", correlation_id: "cor-inc-1", config_version: 1, actions: { retry: permission(false, "이미 처리 중인 작업은 재시도할 수 없습니다."), cancel: permission(true, "미리보기 작업 취소가 가능합니다.") } },
  { id: "job-2203", type: "VOC 패턴 집계", tenant_id: "홍대점", incident_id: "inc-2", status: "QUEUED", queued_at: "2026-10-02T09:55:00Z", attempts: 0, max_attempts: 3, priority: "P2", correlation_id: "cor-inc-2", config_version: 1, actions: { retry: permission(false, "대기 중인 작업은 재시도가 필요하지 않습니다."), cancel: permission(true, "미리보기 작업 취소가 가능합니다.") } },
  { id: "job-2198", type: "공급사 이력 동기화", tenant_id: "판교점", incident_id: "inc-4", status: "FAILED", queued_at: "2026-10-02T09:37:00Z", attempts: 2, max_attempts: 3, priority: "P2", correlation_id: "cor-inc-4", config_version: 1, error_summary: "일시적 연결 시간 초과로 동기화에 실패했습니다.", actions: { retry: permission(true, "재시도 한도 내의 일시적 오류입니다."), cancel: permission(true, "미리보기 작업 취소가 가능합니다.") } },
  { id: "job-2195", type: "로트 매핑 재처리", tenant_id: "판교점", incident_id: "inc-4", status: "DLQ", queued_at: "2026-10-02T09:10:00Z", attempts: 3, max_attempts: 3, priority: "P3", correlation_id: "cor-inc-4", config_version: 1, error_summary: "스키마 변경으로 시도 한도를 초과했습니다. 원본과 오류를 보존했습니다.", actions: { retry: permission(false, "필드 매핑 검토가 완료될 때까지 재처리를 제한합니다."), cancel: permission(false, "감사 보존 대상 작업은 취소할 수 없습니다.") } },
];
export const dashboardFixture: DashboardSnapshot = { as_of: previewTime, incident_trend: [{ day: "09/26", detected: 4, resolved: 3 }, { day: "09/27", detected: 5, resolved: 4 }, { day: "09/28", detected: 3, resolved: 4 }, { day: "09/29", detected: 6, resolved: 5 }, { day: "09/30", detected: 4, resolved: 4 }, { day: "10/01", detected: 7, resolved: 5 }, { day: "10/02", detected: 4, resolved: 1 }], root_cause_distribution: [{ label: "설비 성능", count: 6 }, { label: "작업 절차", count: 4 }, { label: "입고 정합성", count: 3 }, { label: "포장 품질", count: 2 }], capa_status: [{ status: "PROPOSED", count: 5 }, { status: "APPROVED", count: 3 }, { status: "EXECUTED", count: 7 }] };
export const configFixture: ConfigWorkspace = {
  config: { version: 1, default_llm_provider: "gemini", fallback_llm_provider: "ollama", jev_enabled: false, max_agent_iterations: 8, max_tool_calls: 24, parallelism: 4, timeout_seconds: 90, token_budget: 30000, cost_budget_usd: 3, gemini_concurrency: 3, gemini_rate_limit: 60, gemini_timeout_seconds: 45, auto_investigation: true, auto_rca_draft: true, auto_capa_draft: false, auto_execute: false, approval_policy_by_risk: { LOW: false, MEDIUM: false, HIGH: true, CRITICAL: true }, tenant_queue_concurrency: 2, retry_limit: 2 },
  revisions: [], scope: "테넌트 · 본사 운영", allowed_tools: ["evidence.search", "inventory.lookup", "history.query"], verification_window_hours: 2,
  save_permission: permission(true, "운영 설정의 미리보기 변경을 저장할 수 있습니다."), rollback_permission: permission(true, "기존 버전을 기준으로 새 버전을 생성할 수 있습니다."),
  rules: { max_agent_iterations: { min: 1, max: 20, integer: true }, max_tool_calls: { min: 1, max: 50, integer: true }, parallelism: { min: 1, max: 10, integer: true }, timeout_seconds: { min: 5, max: 600, integer: true }, token_budget: { min: 100, max: 100000, integer: true }, cost_budget_usd: { min: 0.01, max: 100, integer: false }, gemini_concurrency: { min: 1, max: 10, integer: true }, gemini_rate_limit: { min: 1, max: 120, integer: true }, gemini_timeout_seconds: { min: 5, max: 600, integer: true }, tenant_queue_concurrency: { min: 1, max: 10, integer: true }, retry_limit: { min: 0, max: 5, integer: true } },
};
const stepNames = ["Jev Decision", "LangGraph", "Investigation fan-out", "Transaction Agent", "Inventory Agent", "Lot Agent", "Supplier Agent", "History Agent", "Evidence Aggregation", "RCA Agent", "CAPA Agent", "Human Approval"];
export const agentFixture: AgentRun = { id: "run-1", incident_id: "inc-1", status: "RUNNING", config_version: 1, correlation_id: "cor-inc-1", steps: stepNames.map((name, index) => ({ id: `step-${index}`, name, status: index === 11 ? "PENDING" : "COMPLETED", latency_ms: index === 11 ? 0 : 120 + index * 45, retry_count: index === 5 ? 1 : 0, token_usage: index === 11 ? 0 : 300 + index * 85, cost_usd: index === 11 ? 0 : 0.004 + index * 0.002, decision_summary: index === 11 ? "사람의 검토 결정을 기다리고 있습니다." : `${["조사 경로 선택", "워크플로 시작", "전문 조사 병렬 분배", "거래 기록 확인", "재고 영향 확인", "로트 증빙 확인", "공급사 이력 확인", "재발 이력 확인", "증거 통합", "원인 후보 작성", "조치안 작성"][index]} 결과를 다음 단계에 전달했습니다.`, tool_calls: index === 0 || index === 11 ? [] : [{ id: `tool-${index}`, name: "evidence.search", status: "SUCCESS", latency_ms: 90, summary: "관련 운영 기록을 읽기 전용으로 조회했습니다." }], ...(index === 10 ? { state_transition: { from: "ACTION_PROPOSED", to: "PENDING_APPROVAL" } as const } : {}) })) };
