export type IncidentStatus = "DETECTED" | "TRIAGED" | "INVESTIGATING" | "RCA_READY" | "ACTION_PROPOSED" | "PENDING_APPROVAL" | "EXECUTING" | "VERIFYING" | "RESOLVED" | "CLOSED" | "ESCALATED" | "BLOCKED" | "FAILED" | "REOPENED";
export type Severity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type Evidence = { id: string; source: string; type: string; summary: string; confidence: number; status: "AVAILABLE" | "PENDING" | "REJECTED" };
export type RootCauseCandidate = { id: string; summary: string; confidence: number; supporting_evidence_ids: string[]; counter_evidence_ids: string[] };
export type CorrectiveAction = { id: string; summary: string; risk_level: Severity; expected_effect: string; verification_criteria: string; status: "PROPOSED" | "APPROVED" | "EXECUTED" };
export type Verification = { id: string; result: "PASS" | "FAIL" | "INCONCLUSIVE"; summary: string; verified_at?: string };
export type ActionPermission = { allowed: boolean; reason: string };
export type Approval = { id: string; incident_id: string; type: string; risk_level: Severity; requester: string; requested_at: string; evidence_completeness: number; status: "PENDING" | "APPROVED" | "REJECTED"; version?: number; actions: Record<"approve" | "edit" | "reject" | "request_more_evidence", ActionPermission> };
export type Incident = { id: string; display_id: string; title: string; severity: Severity; status: IncidentStatus; store: string; owner: string; created_at: string; sla_due_at: string; priority?: "P1" | "P2" | "P3"; version?: number; timeline: Array<{ status: IncidentStatus; occurred_at: string; reason?: string }>; evidence: Evidence[]; root_cause_candidates: RootCauseCandidate[]; corrective_actions: CorrectiveAction[]; verification?: Verification | null };
export type ToolCall = { id: string; name: string; status: "SUCCESS" | "FAILED"; latency_ms: number; summary: string };
export type AgentStep = { id: string; name: string; status: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED"; latency_ms: number; retry_count: number; token_usage: number; cost_usd: number; decision_summary: string; tool_calls: ToolCall[]; state_transition?: { from: IncidentStatus; to: IncidentStatus } };
export type AgentRun = { id: string; incident_id: string; status: "RUNNING" | "COMPLETED" | "FAILED"; steps: AgentStep[]; config_version?: number; correlation_id?: string };
export type ControlPlaneConfig = { version: number; default_llm_provider: "gemini"; fallback_llm_provider: "ollama"; jev_enabled: boolean; max_agent_iterations: number; max_tool_calls: number; parallelism: number; timeout_seconds: number; token_budget: number; cost_budget_usd: number; gemini_concurrency: number; gemini_rate_limit: number; gemini_timeout_seconds: number; auto_investigation: boolean; auto_rca_draft: boolean; auto_capa_draft: boolean; auto_execute: boolean; approval_policy_by_risk: Record<Severity, boolean>; tenant_queue_concurrency: number; retry_limit: number };
export type QueueJob = { id: string; tenant_id: string; type: string; status: "QUEUED" | "PENDING" | "RUNNING" | "FAILED" | "DLQ" | "COMPLETED" | "CANCELLED"; queued_at: string; attempts: number; max_attempts: number; priority: "P1" | "P2" | "P3"; incident_id?: string; correlation_id: string; config_version: number; error_summary?: string; error_code?: string; version?: number; parent_job_id?: string; available_at?: string; started_at?: string; completed_at?: string; lease_until?: string; actions: Record<"retry" | "cancel", ActionPermission> };

export type ReviewAction = keyof Approval["actions"];
export type ReviewDetail = { approval_id: string; incident_display_id: string; incident_title: string; proposed_action: string; expected_effect: string; verification_criteria: string; due_at: string; evidence: Evidence[]; history: Array<{ occurred_at: string; actor: string; summary: string }> };
export type IncidentTask = { id: string; title: string; owner: string; due_at: string; status: "PENDING" | "RUNNING" | "COMPLETED" };
export type IncidentWorkspace = { priority: "P1" | "P2" | "P3"; tasks: IncidentTask[]; actions: Record<"investigate" | "propose_action" | "execute", ActionPermission>; commands?: Record<string, ActionPermission> };
export type Integration = { id: string; name: string; category: string; description: string; status: "HEALTHY" | "DEGRADED" | "DISCONNECTED"; last_success_at: string; error_summary?: string; canonical_model: string; mappings: Array<{ source: string; target: string }>; sync: { started_at: string; ended_at: string; read_count: number; written_count: number; skipped_count: number; error_count: number; cursor_before: string; cursor_after: string }; actions: Record<"sync", ActionPermission> };
export type DashboardSnapshot = {
  as_of: string;
  window: "7d";
  timezone: "UTC";
  kpis: { open_incidents: number; critical_incidents: number; pending_approvals: number; failed_jobs: number; dlq_jobs: number; queue_depth: number; running_jobs: number };
  incident_trend: Array<{ day: string; detected: number; resolved: number }>;
  root_cause_distribution: Array<{ label: string; count: number }>;
  capa_status: Array<{ status: "PROPOSED" | "APPROVED" | "EXECUTED"; count: number }>;
  integration_health: { status: "NOT_IMPLEMENTED"; reason: string };
  priority_incidents: Array<Pick<Incident, "id" | "title" | "store" | "owner" | "severity">>;
};
export type ConfigFieldRule = { min: number; max: number; integer: boolean };
export type ConfigRevision = { version: number; created_at: string; actor: string; reason: string; changes: Array<{ field: string; before: string; after: string }>; snapshot: ControlPlaneConfig };
export type ConfigWorkspace = { config: ControlPlaneConfig; revisions: ConfigRevision[]; rules: Partial<Record<keyof ControlPlaneConfig, ConfigFieldRule>>; save_permission: ActionPermission; rollback_permission: ActionPermission; scope: string; allowed_tools: string[]; verification_window_hours: number };
