"""실행 이력 저장 기술과 조사 로직을 분리합니다."""
from typing import Protocol

from src.agents.models import AgentRun, AgentStep


class AgentRunsUnavailable(Exception):
    """실행 이력 저장소를 사용할 수 없습니다."""


class AgentRunRepository(Protocol):
    def get(self, run_id: str) -> AgentRun | None: ...
    def by_job(self, job_id: str) -> AgentRun | None: ...
    def history(self, incident_id: str, limit=20, offset=0) -> list[AgentRun]: ...
    def save(self, run: AgentRun) -> AgentRun: ...
    def append_step(self, step: AgentStep) -> None: ...
    def steps(self, run_id: str) -> list[AgentStep]: ...
