import { useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { ClipboardList, FlaskConical, SearchCheck, ShieldAlert, X } from "lucide-react";
import { incidentApi } from "../../api/incidents";
import type { Incident } from "../../contracts/types";
import { Badge } from "./IncidentList";

export function IncidentDetail({ id, onBack }: { id: string; onBack: () => void }) {
  const [incident, setIncident] = useState<Incident>(); const [failed, setFailed] = useState(false);
  useEffect(() => { void incidentApi.getIncident(id).then((item) => { if (!item) setFailed(true); else setIncident(item); }).catch(() => setFailed(true)); }, [id]);
  const body = failed ? <div className="state-message error"><div><strong>인시던트를 찾을 수 없습니다</strong><p>삭제되었거나 현재 접근할 수 없는 항목입니다.</p></div></div> : !incident ? <div className="state-message"><div><strong>인시던트 상세 정보를 불러오는 중입니다</strong><p>관련 증거와 조치 정보를 준비하고 있습니다.</p></div></div> : <><div className="page-heading"><div><div className="mb-2 flex gap-2"><Badge value={incident.severity} /><Badge value={incident.status} kind="status" /></div><h1>{incident.title}</h1><p>{incident.display_id} · {incident.store} · 담당 {incident.owner}</p></div></div><div className="metadata"><span className="metadata-item"><strong>발생 시각</strong>{new Date(incident.created_at).toLocaleString("ko-KR")}</span><span className="metadata-item"><strong>SLA</strong>{new Date(incident.sla_due_at).toLocaleString("ko-KR")}까지</span><span className="metadata-item"><strong>현재 단계</strong>{incident.status}</span></div><div className="panel mt-4"><h2><ClipboardList size={17} /> 상태 진행 이력</h2><ol className="timeline">{incident.timeline.map((event) => <li key={event.occurred_at}><strong>{event.status}</strong><small>{new Date(event.occurred_at).toLocaleString("ko-KR")}</small></li>)}</ol></div><div className="panels"><article className="panel"><h2><SearchCheck size={17} /> 증거</h2>{incident.evidence.length ? incident.evidence.map((evidence) => <p key={evidence.id}><strong>{evidence.source}</strong> · {evidence.type}<br />{evidence.summary} <span className="muted">(신뢰도 {Math.round(evidence.confidence * 100)}%)</span></p>) : <p>아직 수집된 증거가 없습니다.</p>}</article><article className="panel"><h2><FlaskConical size={17} /> 원인 분석</h2>{incident.root_cause_candidates.length ? incident.root_cause_candidates.map((candidate) => <p key={candidate.id}><strong>{candidate.summary}</strong><br />신뢰도 {Math.round(candidate.confidence * 100)}% · 뒷받침 증거 {candidate.supporting_evidence_ids.length}건 · 반대 증거 {candidate.counter_evidence_ids.length}건</p>) : <p>조사가 진행되면 원인 후보가 표시됩니다.</p>}</article><article className="panel"><h2><ShieldAlert size={17} /> 시정·예방 조치(CAPA)</h2>{incident.corrective_actions.length ? incident.corrective_actions.map((action) => <p key={action.id}><strong>{action.summary}</strong><br />위험도 {action.risk_level} · 기대 효과: {action.expected_effect}<br />검증 기준: {action.verification_criteria}</p>) : <p>원인 분석 후 조치안이 제안됩니다.</p>}</article><article className="panel"><h2><SearchCheck size={17} /> 검증 결과</h2><p><strong>{incident.verification?.result === "PASS" ? "통과" : incident.verification?.result === "FAIL" ? "실패" : "판정 보류"}</strong><br />{incident.verification?.summary ?? "조치 실행 후 검증을 진행합니다."}</p></article></div></>;
  return <Dialog.Root open onOpenChange={(open) => { if (!open) onBack(); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="dialog-content"><header className="dialog-header"><Dialog.Title>인시던트 상세</Dialog.Title><Dialog.Close className="dialog-close" aria-label="상세 팝업 닫기"><X size={19} /></Dialog.Close></header><div className="dialog-body"><section className="page">{body}</section></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
